#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    uv run --group dev hass --config "${PWD}/config" --script ensure_config
fi

export PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${PWD}/custom_components"

uv run --group dev hass --config "${PWD}/config" --debug
